---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: zync-que
  namespace: 3scale
spec:
  template:
    spec:


      volumes:
        - name: zync-ca-bundle
          configMap:
            name: zync-ca-bundle
            items:
              - key: zync.pem
                path: zync.pem
            defaultMode: 420