apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: echo-api-product-sample
spec:
  applicationPlans:
    plan_basic:
      limits:
        - metricMethodRef:
            systemName: hits
          period: day
          value: 30
      name: Basic
    plan_unlimited:
      name: Unlimited
  providerAccountRef:
    name: tenant-secret
  name: Operated Product Echo API
  systemName: echo_api_product
  description: Echo API Product
  backendUsages:
    echo_api_backend:
      path: /
  deployment:
    apicastHosted:
      #stagingPublicBaseURL: "https://apis-3scale-dev-staging.apps.cluster-v2pdq.v2pdq.sandbox2054.opentlc.com"
      #productionPublicBaseURL: "https://apis-3scale-dev.apps.cluster-v2pdq.v2pdq.sandbox2054.opentlc.com"
      authentication:
        oidc:
          issuerType: "keycloak"
          issuerEndpoint: "https://testclient:7wyDCDc5yr6Nur1OD5bdHJQdUbRYIeRT@keycloak-rhsso-dev.apps.cluster-t2xqd.t2xqd.sandbox2018.opentlc.com/auth/realms/dev"