apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base-operator
configurations:
  - config.yaml
generatorOptions:
 disableNameSuffixHash: true
# secretGenerator:
# - name: keycloak-db-secret
#   envs:
#   - env/bd-credential.env
# - name: credential-keycloak
#   envs:
#   - env/sso-credential.env
configMapGenerator:
- name: zync-ca-bundle
  files:
  - resources/certs/zync.pem

# patches:
# - patch: |-
#     - op: add
#       path: /spec/template/spec/volumes-
#       value: 
#         - name: zync-ca-bundle
#           configMap:
#             name: zync-ca-bundle
#             items:
#               - key: zync.pem
#                 path: zync.pem
#             defaultMode: 420
#   target:
#     group: apps.openshift.io
#     kind: DeploymentConfig
#     name: zync-que
#     version: v1
patchesStrategicMerge:
  - resources/patches/zync-que.yaml
# replacements:
#   - path: image-tag-replacement.yaml

resources: 
#- namespace.yaml
- resources/3scale-instance.yaml
- resources/secret-s3-auth.yaml
- resources/clusterrole.yaml

# dev tenant
- resources/dev-tenant-namespace.yaml
- resources/dev-admin-secret.yaml
- resources/dev-tenant.yaml

vars:
  - name: DOMAIN
    objref:
      apiVersion: apps.3scale.net/v1alpha1
      kind: APIManager
      name: apimanager-sample
    fieldref:
      fieldpath: spec.wildcardDomain

