kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 3scale-read
subjects:
  - kind: ServiceAccount
    name: 3scale-operator
    namespace: 3scale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 3scale-operator-ns-admin
