---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  generation: 1
  name: 3scale
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: 3scale-api-dev-declations
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: 3scale-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: overlays/api-dev-declarations
# we specify the folder for the files
    repoURL: 'https://github.com/mcaballol/gitops-deploy-3scale.git'
# the repository url
    targetRevision: main
# and branch, in this case HEAD / main 
  project: 3scale
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    retry:
      limit: 10
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
      # annotations:
      #   argocd.argoproj.io/sync-wave: "0"

    syncOptions:
    - CreateNamespace=true