---
kind: DeveloperAccount
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: clh-area1
spec:
  orgName: clh-area1
  providerAccountRef:
    name: dev-tenant-secret
---
kind: DeveloperUser
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: user1-clh
spec:
  developerAccountRef:
    name: clh-area1
  email: user1clh@example.com
  role: admin
  username: user1-clh
  passwordCredentialsRef:
    name: dev-user-secret
  providerAccountRef:
    name: dev-tenant-secret