---
kind: DeveloperAccount
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: clh-area2
spec:
  orgName: clh-area2
  providerAccountRef:
    name: dev-tenant-secret
---
kind: DeveloperUser
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: user2-clh
spec:
  developerAccountRef:
    name: clh-area2
  email: user2-clh@example.com
  role: admin
  username: user2-clh
  passwordCredentialsRef:
    name: dev-user-secret
  providerAccountRef:
    name: dev-tenant-secret